on:
  release:
    types: [created]

jobs:
  release-windows-amd64:
    name: release windows 64-bit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.25
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          goos: windows
          goarch: amd64
          ldflags: "-w -s -H windowsgui"
          pre_command: "apt-get update && apt-get install --no-install-recommends -y gcc-mingw-w64 && export CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc"